# Data Description

# Documents the origin and preparation of data files supplied with dnaEPICO.
# This script is not run during package installation.

# -----------------------------------------------------------
# Data sources
# -----------------------------------------------------------

# 1. Probe-exclusion list:
#   12864_2024_10027_MOESM8_ESM.csv
#
# This supplementary file is used to demonstrate probe filtering. Its size was
# reduced to less than 100 MB for package distribution.
#
# Source URL:
#   https://link.springer.com/article/10.1186/s12864-024-10027-5
#
#
# 2. Cell composition reference coefficients (Houseman method):
#
#   saliva.txt
#   salivaEPIC.txt
#
# `estimateLC()` uses these coefficient matrices to estimate cell-type
# proportions from DNA methylation beta values with the Houseman algorithm.
#
# The reference data originate from the ewastools pipeline:
#
#   Murat K, et al. (2020)
# "Ewastools: Infinium Human Methylation BeadChip pipeline for
#    population epigenetics integrated into Galaxy."
# GigaScience, 9(5):giaa049.
# https://academic.oup.com/gigascience/article/9/5/giaa049/5836679
#
# The saliva reference panel corresponds to:
#
#   Middleton LYM, et al. (2020)
# "Saliva cell type DNA methylation reference panel for
#    epidemiology studies in children."
# https://pubmed.ncbi.nlm.nih.gov/33588693/

# -----------------------------------------------------------
# Make/ directory
# -----------------------------------------------------------

# The `make/` directory contains the exported workflow configuration and rules.
# These files are not run during package installation.
#
# Files in the `make/` directory include:
#
#   - Rules for preprocessing, modelling, and reporting steps
#   - Model-specific configuration variables

# -----------------------------------------------------------
# dnaEPICO logo/report graphics
# -----------------------------------------------------------

# dnaEPICO.gif is the animated logo used in the vignette and README files.
# dnaEPICORM.svg is the packaged logo used by `dnamReport()`, README, and
# vignette files.
# dnam-report.css is a CSS stylesheet used to style the report generated by `dnamReport()`.
# cpg-viewer.js renders paged CpG result tables in the report.
# figure-viewer.js is a JavaScript library used to render interactive figures in the report.
# report-interactions.js is a JavaScript library used to render interactive report elements.

# -----------------------------------------------------------
# Final location in the package
# -----------------------------------------------------------

# The prepared files were placed in:
#
#   inst/extdata/
#
#   - 12864_2024_10027_MOESM8_ESM.csv
#   - saliva.txt
#   - salivaEPIC.txt
#   - dnaEPICORM.svg
#   - dnaEPICO.gif
#   - dnam-report.css
#   - cpg-viewer.js
#   - figure-viewer.js
#   - report-interactions.js

# inst/extdata/make/
#
#   - Workflow reproducible pipeline execution files
